evaluation:
  promise_id: llm-input-logging
  severity: high
  threshold: 0.95
  thresholds:
    high: 0.95
  pytest_targets: []
  semgrep_rules_path: governance/evidence/semgrep_rules.yaml
promises:
  - llm-input-logging
  - llm-privacy-redaction
  - llm-prompt-injection-defense
hooks: []
